name: Build and Publish Paper
on: [push, pull_request]
jobs:
  CompileAndPublishLaTeXPaper:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: LaTeX Build and Publish Paper
        uses: adgsenpai/LaTeXCompiler@v1.0.2

